name: Unity Builder
description: unity build command library
author: https://github.com/qkrsogusl3
requirements: []
configuration:
  properties:
    app-center:
      type: object
      optional: true
      properties:
        name:
          type: string
        token:
          type: string
        id:
          type: number
  additionalProperties: false
