version: "2"
services:
  unity:
    env_file:
        - ".env"
    build:
      context: .
      args:
        GAME_CI_UNITY_EDITOR_IMAGE: ${GAME_CI_UNITY_EDITOR_IMAGE}
        PLATFORM: ${PLATFORM}
        UNITY_LICENSE: ${UNITY_LICENSE}
        DOCKER_FASTLANE: ${DOCKER_FASTLANE}
    image: ${IMAGE_TO_PUBLISH}
    environment:
      FL_UNITY_PROJECT_PATH: /app
      FL_UNITY_PATH: unity-editor
